version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install -g pnpm
      - pnpm install

  build:
    commands:
      - echo Building the app...
      - pnpm run build

artifacts:
  base-directory: dist
  files:
    - 'dist/*'